= image:../logo.svg[] Boat Spring Boot: SrcLab Core Libraries for Spring Boot and {boat-url}[Boat]
:toc:
:toclevels: 3
:last-update-label!:
Sun Qian <fredsuvn@163.com>
:encoding: UTF-8
:emaill: fredsuvn@163.com
:url: https://github.com/srclab-projects/boat-spring-boot
:boat-url: https://github.com/srclab-projects/boat
:boat-spring-boot-version: 0.0.1

== Introduction

Boat Spring Boot is spring-boot framework supporting with {boat-url}[Boat].
It provides many fast and convenient interfaces and utilities adapted for spring-boot framework.

Boat Spring Boot includes:

* <<Core (boat-spring-boot-core)>>: Core and basic interfaces and utilities;
* <<Web (boat-spring-boot-web)>>: Web interfaces and utilities;
* `boat-spring-boot-test`: Testing libs dependencies management project;
* `boat-spring-boot-bom`: BOM (gradle platform) project;

To import those modules, use their `starters`:

* `boat-spring-boot-starter`
* `boat-spring-boot-web-starter`
* `boat-spring-boot-starter-test`
* `boat-spring-boot-starter-bom`

== Getting

.Gradle
[source,groovy,subs="attributes+"]
----
implementation("xyz.srclab.spring.boot:boat-spring-boot-starter:{boat-spring-boot-version}")
----

.Maven
[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>xyz.srclab.spring.boot</groupId>
    <artifactId>boat-spring-boot-starter</artifactId>
    <version>{boat-spring-boot-version}</version>
</dependency>
----

.Source Code
{url}

== Usage

=== Core (boat-spring-boot-core)

==== Core

Core package provides core interfaces and utilities:

* `KeyString`: Represents a key string may be encoded and encrypted, mainly used for non-plain text configure;
* `StartGreeting`: Interface to define whether and how to show the greeting message when started;
* `GreetingProperties`: Properties for `StartGreeting`;

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/core/KeyStringSample.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/core/TestKeyString.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/core/GreetingSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/core/KeyStringSample.kt[]
----

[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/core/GreetingSample.kt[]
----

==== Bean

Bean package provides:

* `BeanProperties`: Properties for bean configure;
* `BeanLifecyclePostProcessor`: Spring Bean lifecycle post processor;
* `BeanRegistry`: Dynamic bean registry;

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/bean/BeanSample.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/bean/MyBeanLifecyclePostProcessor.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/bean/MyBean.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/bean/MyBeanRegistry.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/bean/MyBeanLifecyclePostProcessor.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/bean/BeanSample.kt[]
----

[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/bean/MyBeanLifecyclePostProcessor.kt[]
----

==== Message

Message package provides:

* `ReqMessage`: Convenient request message definition;
* `RespMessage`: Convenient response message definition;

==== Task

Task package provides:

* `TaskPoolProperties`: Properties for task thread pool;
* `TaskExecutors`: Help fast create `TaskExecutor` with `ThreadPoolProperties`;
* `TaskDelegate`: Task execution delegate;

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/task/TaskSample.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/task/AsyncService.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/task/TaskExecutorConfiguration.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/task/TaskSample.kt[]
----

==== Schedule

Schedule package provides:

* `ScheduledPoolProperties`: Properties for scheduled thread pool;
* `TaskSchedulers`: Help fast create `TaskScheduler` with `ScheduledPoolProperties`;

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/schedule/ScheduleSample.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/schedule/ScheduleService.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/schedule/TaskSchedulerConfiguration.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/schedule/ScheduleSample.kt[]
----

==== Exception

Exception package provides:

* `EnableExceptionHandlingService`: Annotation to enable global exception handling service;
* `ExceptionHandlingService`: Autowired global exception handling service, see its javadoc for more detail;
* `ExceptionHandlingComponent`, `ExceptionHandlingMethod`: Annotations to provide exception handler for `ExceptionHandlingService`;

.Java Examples
[source,java]
----
include::../boat-spring-boot-core/src/test/java/test/xyz/srclab/spring/boot/exception/ExceptionServiceTest.java[]
----

[source,java]
----
include::../boat-spring-boot-core/src/test/java/test/xyz/srclab/spring/boot/exception/ExceptionHandler.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/exception/ExceptionServiceSample.kt[]
----

=== Web (boat-spring-boot-web)

==== Exception

Web exception package provides:

* `EnableWebExceptionHandling`: Annotation to enable global web exception service;
* `WebStatusException`: Exception for web;
* `ExceptionResponseBody`: Exception response body for web;

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/exception/WebExceptionSample.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/exception/TestController.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/exception/ExceptionHandler.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/web/exception/WebExceptionSample.kt[]
----

==== Servlet

Servlet package provides:

* `WebServlets`: Provides Servlet tools, such as fast build for `ServletRequest`, `ServletInputStream`;

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/servlet/ServletSample.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/servlet/TestController.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/servlet/TestFilter.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/web/servlet/ServletSample.kt[]
----