= image:../logo.svg[] Boat Spring Boot: 基于 Spring Boot 和  {boat-url}[Boat] 的 SrcLab 核心库
:toc:
:toclevels: 3
:toc-title: 目录
:last-update-label!:
Sun Qian <fredsuvn@163.com>
:encoding: UTF-8
:emaill: fredsuvn@163.com
:url: https://github.com/srclab-projects/boat-spring-boot
:boat-url: https://github.com/srclab-projects/boat
:boat-spring-boot-version: 0.0.1

== Introduction

Boat Spring Boot 是使用 {boat-url}[Boat] 来支持 spring-boot 框架的库.
它提供许多快速方便的接口和工具, 适配 spring-boot 框架.

Boat Spring Boot 包括:

* <<Core (boat-spring-boot-core)>>: 核心基础接口和工具;
* <<Web (boat-spring-boot-web)>>: Web接口和工具;
* `boat-spring-boot-test`: 测试库依赖管理项目;
* `boat-spring-boot-bom`: BOM (gradle platform) 项目;

想要导入以上模块, 请使用``starters``:

* `boat-spring-boot-starter`
* `boat-spring-boot-web-starter`
* `boat-spring-boot-starter-test`
* `boat-spring-boot-starter-bom`

== 获取

.Gradle
[source,groovy,subs="attributes+"]
----
implementation("xyz.srclab.spring.boot:boat-spring-boot-starter:{boat-spring-boot-version}")
----

.Maven
[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>xyz.srclab.spring.boot</groupId>
    <artifactId>boat-spring-boot-starter</artifactId>
    <version>{boat-spring-boot-version}</version>
</dependency>
----

.源代码
{url}

== 用法

=== Core (boat-spring-boot-core)

==== Core

Core包提供核心接口和工具:

* `KeyString`: 代表经过编码和加密的字符串, 主要用于非明文配置配置;
* `StartGreeting`: 定义启动问候信息的接口;
* `GreetingProperties`: `StartGreeting` 的配置;

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/core/KeyStringSample.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/core/TestKeyString.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/core/GreetingSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/core/KeyStringSample.kt[]
----

[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/core/GreetingSample.kt[]
----

==== Bean

Bean包提供:

* `BeanProperties`: Bean相关配置;
* `BeanLifecyclePostProcessor`: Spring Bean 生命周期后置处理器;
* `BeanRegistry`: 动态bean注册;

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/bean/BeanSample.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/bean/MyBeanLifecyclePostProcessor.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/bean/MyBean.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/bean/MyBeanRegistry.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/bean/MyBeanLifecyclePostProcessor.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/bean/BeanSample.kt[]
----

[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/bean/MyBeanLifecyclePostProcessor.kt[]
----

==== Message

Message包提供:

* `ReqMessage`: 方便的请求消息定义;
* `RespMessage`: 方便的返回消息定义;

==== Task

Task包提供:

* `TaskPoolProperties`: Task线程池相关配置;
* `TaskExecutors`: 使用 `ThreadPoolProperties` 快速构建 `TaskExecutor`;
* `TaskDelegate`: Task执行委托器;

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/task/TaskSample.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/task/AsyncService.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/task/TaskExecutorConfiguration.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/task/TaskSample.kt[]
----

==== Schedule

Schedule包提供:

* `ScheduledPoolProperties`: 调度器的线程池相关配置;
* `TaskSchedulers`: 使用 `ScheduledPoolProperties` 快速构建 `TaskScheduler`;

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/schedule/ScheduleSample.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/schedule/ScheduleService.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/schedule/TaskSchedulerConfiguration.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/schedule/ScheduleSample.kt[]
----

==== Exception

Exception包提供:

* `EnableExceptionHandlingService`: 启动全局异常处理服务的注解;
* `ExceptionHandlingService`: 全局异常处理服务, 详情请参阅其javadoc;
* `ExceptionHandlingComponent`, `ExceptionHandlingMethod`: 为 `ExceptionHandlingService` 提供异常处理器的注解;

.Java Examples
[source,java]
----
include::../boat-spring-boot-core/src/test/java/test/xyz/srclab/spring/boot/exception/ExceptionServiceTest.java[]
----

[source,java]
----
include::../boat-spring-boot-core/src/test/java/test/xyz/srclab/spring/boot/exception/ExceptionHandler.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/exception/ExceptionServiceSample.kt[]
----

=== Web (boat-spring-boot-web)

==== Exception

Web exception 包提供:

* `EnableWebExceptionHandling`: 开启Web全局异常处理的注解;
* `WebStatusException`: Web异常基类;
* `ExceptionResponseBody`: Web异常信息消息体;

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/exception/WebExceptionSample.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/exception/TestController.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/exception/ExceptionHandler.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/web/exception/WebExceptionSample.kt[]
----

==== Servlet

Servlet包提供:

* `WebServlets`: 提供 `Servlet` 相关工具, 如快速构建 `ServletRequest`, `ServletInputStream`;

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/servlet/ServletSample.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/servlet/TestController.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/servlet/TestFilter.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/web/servlet/ServletSample.kt[]
----