= image:../logo.svg[Boat Spring Boot] Boat Spring Boot: SrcLab Core Libraries for Spring Boot
:toc:
:toclevels: 3
:last-update-label!:
Sun Qian <fredsuvn@163.com>
:encoding: UTF-8
:emaill: fredsuvn@163.com
:url: https://github.com/srclab-projects/boat-spring-boot
:license: https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license]

:qq-group: QQ group: 1037555759
:boat-url: https://github.com/srclab-projects/boat
:boat-spring-boot-version: 0.0.0

== Introduction

Boat Spring Boot is a set of spring-boot projects with {boat-url}[Boat].
It provides many fast and convenient interfaces, functions and utilities adapted to spring-boot with {boat-url}[Boat].

Boat Spring Boot includes:

* *boat-spring-boot-core*: Core and basic interfaces, functions and utilities, such as spring bean operation;
* *boat-spring-boot-test*: Test dependencies management, to import common test libraries in test scope;
* *boat-spring-boot-bom*: Boat Spring Boot Bom.

Following the official recommendation of Spring Boot, we should use starter to import Boat Spring Boot:

* boat-spring-boot-starter
* boat-spring-boot-starter-test
* boat-spring-boot-starter-bom

== Getting

.Gradle
[source,groovy,subs="attributes+"]
----
implementation("xyz.srclab.spring.boot:boat-spring-boot-starter:{boat-spring-boot-version}")
----

.Maven
[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>xyz.srclab.spring.boot</groupId>
    <artifactId>boat-spring-boot-starter</artifactId>
    <version>{boat-spring-boot-version}</version>
</dependency>
----

.Source Code
https://github.com/srclab-projects/boat-spring-boot

== Usage

=== Core (boat-spring-boot-starter)

==== Bean

Bean provides:

* BeanProperties: Properties for bean;
* BeanLifecyclePostProcessor: Spring Bean lifecycle post processor;
* BeanRegistry: Dynamic bean registry.

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/bean/MyBeanRegistry.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/bean/MyBeanLifecyclePostProcessor.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/bean/MyBeanRegistry.kt[]
----

[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/bean/MyBeanLifecyclePostProcessor.kt[]
----

==== Task

Task provides:

* TaskPoolProperties: Properties for task thread pool;
* TaskExecutors: Help fast create TaskExecutor with ThreadPoolProperties;
* TaskDelegate: Task execution delegate.

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/task/MyTaskExecutorConfiguration.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/task/MyTaskExecutorConfigurationKt.kt[]
----

==== Schedule

Schedule provides:

* ScheduledPoolProperties: Properties for scheduled thread pool;
* TaskSchedulers: Help fast create TaskScheduler with ScheduledPoolProperties.

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/schedule/MyTaskSchedulerConfiguration.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/schedule/MyTaskSchedulerConfiguration.kt[]
----

==== Exception

Exception provides:

* EnableExceptionService: Annotation to enable exception service;
* ExceptionStatusService: Auto-created global exception processing, use ExceptionStateHandler;
* ExceptionStatusHandler: Handler bean defined by user, to convert exception to State.

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/exception/ExceptionServiceSample.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/exception/RuntimeExceptionStatusHandler.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/exception/ThrowableStatusHandler.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/exception/ExceptionServiceSample.kt[]
----

=== Web (boat-spring-boot-web-starter)

==== Exception

Web exception provides:

* EnableWebExceptionService: Annotation to enable web exception service;
* WebExceptionService: Auto-created global web exception processing, use WebExceptionHandler;
* WebExceptionHandler: Handler bean defined by user, to convert exception to ResponseEntity.

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/exception/WebExceptionSample.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/exception/TestController.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/exception/RuntimeExceptionHandler.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/exception/ThrowableHandler.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/web/exception/WebExceptionSample.kt[]
----

==== Utilities

Some utilities provided by web module:

* WebExceptions: Provides exception tools for web;
* WebServlets: Provides Servlet tools, such as fast build for ServletRequest, ServletInputStream.

== Contribution and Contact

* {emaill}
* {url}
* {qq-group}

== License

{license}