= Boat Spring Boot: SrcLab核心基础Spring Boot库
Sun Qian <fredsuvn@163.com>
:encoding: UTF-8
:license: https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license]
:emaill: fredsuvn@163.com
:url: https://github.com/srclab-projects/boat-spring-boot
:qq: 1037555759
:boat-url: https://github.com/srclab-projects/boat
:boat-spring-boot-version: 0.1.0

image::../logo.svg[Boat Spring Boot]

== 修订

[options="header"]
|===
|日期|修订版|作者|内容
|2020-3-5|1.0.0|{author}|旧项目
|2021-3-5|0.1.0|{author}|新项目
|===

== 目录

* <<introduction>>
* <<getting>>
* <<usage>>
* <<contact>>
* <<license>>

[#introduction]
== 简介

Boat Spring Boot是一组基于{boat-url}[Boat]的spring-boot项目集合.
它在{boat-url}[Boat]的基础上, 提供了许多方便快捷的spring-boot接口, 函数和工具.

Boat Spring Boot包括:

* *boat-spring-boot-core*: 核心和基础的接口, 功能和工具, 比如spring bean操作;
* *boat-spring-boot-test*: 测试依赖管理, 用来在测试编译和运行范围下引入测试框架;
* *boat-spring-boot-bom*: Boat Spring Boot Bom.

根据Spring Boot官方推荐, 我们应当使用starter来导入Boat Spring Boot:

* boat-spring-boot-starter
* boat-spring-boot-starter-test
* boat-spring-boot-starter-bom

[#getting]
== 获取

=== Gradle

[source,groovy,subs="attributes+"]
----
implementation("xyz.srclab.spring.boot:boat-spring-boot-starter:{boat-spring-boot-version}")
----

=== Maven

[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>xyz.srclab.spring.boot</groupId>
    <artifactId>boat-spring-boot-starter</artifactId>
    <version>{boat-spring-boot-version}</version>
</dependency>
----

=== Source Code

https://github.com/srclab-projects/boat-spring-boot

[#usage]
== 使用

* <<usage-core>>
** <<usage-core-bean>>
** <<usage-core-task>>
** <<usage-core-schedule>>
** <<usage-core-exception>>

[#usage-core]
=== Core (boat-spring-boot-starter)

[#usage-core-bean]
==== Bean

Bean提供:

* BeanLifecyclePostProcessor: Spring Bean整个生命周期后置处理器;
* BeanRegistry: 动态bean注册.

===== Java Examples

[source,java]
----
@Component
public class MyBeanRegistry extends BeanRegistry {

    @NotNull
    @Override
    protected Map<String, Object> registeredSingletons() {
        Map<String, Object> result = new HashMap<>();
        result.put("bean1", "bean1");
        result.put("bean2", "bean2");
        return result;
    }

    @NotNull
    @Override
    protected Set<BeanProperties> registeredBeans() {
        Set<BeanProperties> result = new HashSet<>();
        BeanProperties beanProperties = new BeanProperties();
        beanProperties.setName("myBean");
        beanProperties.setClassName(MyBean.class.getName());
        result.add(beanProperties);
        return result;
    }
}
----

===== Kotlin Examples

[source,kotlin]
----
@Component
open class MyBeanRegistry : BeanRegistry() {

    override val registeredSingletons: Map<String, Any>
        get() {
            val result: MutableMap<String, Any> = HashMap()
            result["bean1"] = "bean1"
            result["bean2"] = "bean2"
            return result
        }

    override val registeredBeans: Set<BeanProperties>
        get() {
            val result: MutableSet<BeanProperties> = HashSet()
            val beanProperties = BeanProperties()
            beanProperties.name = "myBean"
            beanProperties.className = MyBean::class.java.name
            result.add(beanProperties)
            return result
        }
}
----

[#usage-core-task]
==== Task

Task提供:

* ThreadPoolProperties: 线程池属性;
* TaskExecutors: 快速创建TaskExecutor, 通常使用ThreadPoolProperties.

===== Java Examples

[source,java]
----
@Configuration
@EnableAsync
public class MyTaskExecutorConfiguration {

    @Bean
    public TaskExecutor taskExecutor() {
        ThreadPoolProperties poolProperties = new ThreadPoolProperties();
        poolProperties.setThreadNamePrefix("6666");
        return TaskExecutors.newTaskExecutor(poolProperties);
    }
}
----

===== Kotlin Examples

[source,kotlin]
----
@Configuration
@EnableAsync
open class MyTaskExecutorConfigurationKt {

    @Bean
    open fun taskExecutor(): TaskExecutor {
        val poolProperties = ThreadPoolProperties()
        poolProperties.threadNamePrefix = "6666"
        return newTaskExecutor(poolProperties)
    }
}
----

[#usage-core-schedule]
==== Schedule

Schedule提供:

* ScheduledPoolProperties: 调度线程池属性;
* TaskSchedulers: 快速创建TaskScheduler, 通常使用ScheduledPoolProperties.

===== Java Examples

[source,java]
----
@Configuration
@EnableScheduling
public class MyTaskSchedulerConfiguration {

    @Bean
    public TaskScheduler taskScheduler() {
        ScheduledPoolProperties poolProperties = new ScheduledPoolProperties();
        poolProperties.setThreadNamePrefix("6666");
        return TaskSchedulers.newTaskScheduler(poolProperties);
    }
}
----

===== Kotlin Examples

[source,kotlin]
----
@Configuration
@EnableScheduling
open class MyTaskSchedulerConfiguration {

    @Bean
    open fun taskScheduler(): TaskScheduler {
        val poolProperties = ScheduledPoolProperties()
        poolProperties.threadNamePrefix = "6666"
        return newTaskScheduler(poolProperties)
    }
}
----

[#usage-core-exception]
==== Exception

异常包提供:

* ExceptionStateHandler: 用户定义的bean, 将异常转为State;
* ExceptionStateService: 自动注入的全局异常处理服务, 使用ExceptionStateHandler;
* EnableExceptionStateService: 开启ExceptionStateService的注解.

===== Java Examples

[source,java]
----
@SpringBootTest(classes = Starter.class)
@EnableExceptionStateService
public class ExceptionStateServiceSample extends AbstractTestNGSpringContextTests {

    @Resource
    private ExceptionStateService exceptionStateService;

    @Test
    public void testExceptionStateService() {
        ExceptionStatus runtime = exceptionStateService.toState(new RuntimeException());
        Assert.assertEquals(runtime.code(), "102");
        ExceptionStatus throwable = exceptionStateService.toState(new Exception());
        Assert.assertEquals(throwable.code(), "101");
    }
}

@Component
public class RuntimeExceptionExceptionStateHandler implements ExceptionStateHandler<RuntimeException, ExceptionStatus> {

    @NotNull
    @Override
    public Class<RuntimeException> supportedExceptionType() {
        return RuntimeException.class;
    }

    @NotNull
    @Override
    public ExceptionStatus handle(@NotNull RuntimeException exception) {
        return ExceptionStatus.of("102");
    }
}

@Component
public class ThrowableExceptionStateHandler implements ExceptionStateHandler<Throwable, ExceptionStatus> {

    @NotNull
    @Override
    public Class<Throwable> supportedExceptionType() {
        return Throwable.class;
    }

    @NotNull
    @Override
    public ExceptionStatus handle(@NotNull Throwable throwable) {
        return ExceptionStatus.of("101");
    }
}
----

===== Kotlin Examples

[source,kotlin]
----
@SpringBootTest(classes = [Starter::class])
@EnableExceptionStateService
class ExceptionStateServiceSample : AbstractTestNGSpringContextTests() {

    @Resource
    private lateinit var exceptionStateService: ExceptionStateService

    @Test
    fun testExceptionStateService() {
        val runtime = exceptionStateService.toState<ExceptionStatus>(RuntimeException())
        Assert.assertEquals(runtime.code, "102")
        val throwable = exceptionStateService.toState<ExceptionStatus>(Exception())
        Assert.assertEquals(throwable.code, "101")
    }
}

@Component
open class RuntimeExceptionExceptionStateHandler :
    ExceptionStateHandler<RuntimeException, ExceptionStatus> {
    override val supportedExceptionType: Class<RuntimeException> = RuntimeException::class.java
    override fun handle(e: RuntimeException): ExceptionStatus {
        return ExceptionStatus.of("102")
    }
}

@Component
open class ThrowableExceptionStateHandler : ExceptionStateHandler<Throwable, ExceptionStatus> {
    override val supportedExceptionType: Class<Throwable> = Throwable::class.java
    override fun handle(e: Throwable): ExceptionStatus {
        return ExceptionStatus.of("101")
    }
}
----

[#contact]
== 共享和联系方式

* {emaill}
* {url}
* QQ群: 1037555759

[#license]
== License

{license}