= image:../logo.svg[Boat Spring Boot] Boat Spring Boot: SrcLab核心基础Spring Boot库
:toc:
:toclevels: 3
:toc-title: 目录
:last-update-label!:
Sun Qian <fredsuvn@163.com>
:encoding: UTF-8
:emaill: fredsuvn@163.com
:url: https://github.com/srclab-projects/boat-spring-boot
:license: https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license]

:qq-group: QQ group: 1037555759
:boat-url: https://github.com/srclab-projects/boat
:boat-spring-boot-version: 0.0.1

== 简介

Boat Spring Boot是一组基于{boat-url}[Boat]的spring-boot项目集合.
它在{boat-url}[Boat]的基础上, 提供了许多方便快捷的spring-boot接口, 函数和工具.

Boat Spring Boot包括:

* *boat-spring-boot-core*: 核心和基础的接口, 功能和工具, 比如spring bean操作;
* *boat-spring-boot-test*: 测试依赖管理, 用来在测试编译和运行范围下引入测试框架;
* *boat-spring-boot-bom*: Boat Spring Boot Bom.

根据Spring Boot官方推荐, 我们应当使用starter来导入Boat Spring Boot:

* boat-spring-boot-starter
* boat-spring-boot-starter-test
* boat-spring-boot-starter-bom

== 获取

.Gradle
[source,groovy,subs="attributes+"]
----
implementation("xyz.srclab.spring.boot:boat-spring-boot-starter:{boat-spring-boot-version}")
----

.Maven
[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>xyz.srclab.spring.boot</groupId>
    <artifactId>boat-spring-boot-starter</artifactId>
    <version>{boat-spring-boot-version}</version>
</dependency>
----

.Source Code
{url}

== 使用

=== Core (boat-spring-boot-starter)

==== Lang

Lang包为spring-boot提供扩展的基础功能:

* EncodeString: 代表一个可能经过编码和加密的属性字段.

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/lang/LangSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/lang/LangSample.kt[]
----

==== Bean

Bean包提供:

* BeanProperties: bean属性;
* BeanLifecyclePostProcessor: Spring Bean整个生命周期后置处理器;
* BeanRegistry: 动态bean注册.

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/bean/MyBeanRegistry.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/bean/MyBeanLifecyclePostProcessor.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/bean/MyBeanRegistry.kt[]
----

[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/bean/MyBeanLifecyclePostProcessor.kt[]
----

==== Message

消息包提供:

* ReqMessage: 方便的请求消息定义;
* RespMessage: 方便的响应消息定义.

==== Task

Task包提供:

* TaskPoolProperties: Task线程池属性;
* TaskExecutors: 快速创建TaskExecutor, 通常使用ThreadPoolProperties;
* TaskDelegate: Task调度委托.

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/task/MyTaskExecutorConfiguration.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/task/MyTaskExecutorConfigurationKt.kt[]
----

==== Schedule

Schedule包提供:

* ScheduledPoolProperties: 调度线程池属性;
* TaskSchedulers: 快速创建TaskScheduler, 通常使用ScheduledPoolProperties.

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/schedule/MyTaskSchedulerConfiguration.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/schedule/MyTaskSchedulerConfiguration.kt[]
----

==== Exception

异常包提供:

* EnableExceptionHandlingService: 开启异常处理服务的注解;
* ExceptionHandlingService: 自动注入的全局异常处理服务, 具体参阅其javadoc;
* ExceptionHandler: 为ExceptionHandlingService处理异常的具体接口.

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/exception/ExceptionServiceSample.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/exception/ThrowableStatusHandler.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/exception/RuntimeExceptionStatusHandler.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/exception/ExceptionServiceSample.kt[]
----

=== Web (boat-spring-boot-web-starter)

==== Exception

Web异常包提供:

* EnableWebExceptionService: 开启Web一场服务的注解;
* WebExceptionService: 自动注入的全局异常服务, 具体请参阅其Javadoc;
* WebExceptionResponseHandler: 将异常转换成ResponseEntity的接口, 为WebExceptionService工作;
* WebStatusException: 针对Web场景的便捷异常.

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/exception/WebExceptionSample.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/exception/TestController.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/exception/ThrowableHandler.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/exception/RuntimeExceptionHandler.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/exception/WebStatusExceptionHandler.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/web/exception/WebExceptionSample.kt[]
----

==== Message

消息包包括:

* HttpReqMessage, HttpRespMessage: 方便的http消息定义;
* HttpReqMessageResolver: 针对HttpReqMessage的参数解析器;
* MessageProperties: Http消息的配置属性;
* EnableHttpReqMessageResolving: 开启HttpReqMessage类型的参数解析, 具体请参阅它的javadoc.

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/message/MessageController.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/message/WebMessageSample.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/web/message/WebMessageSample.kt[]
----

==== Utilities

一些工具类也在web中提供:

* WebExceptions: 提供异常相关的工具方法;
* WebServlets: 提供Servlet工具, 比如针对ServletRequest, ServletInputStream等的快速构建.

== 共享和联系方式

* {emaill}
* {url}
* {qq-group}

== License

{license}