= image:../logo.svg[Boat Spring Boot] Boat Spring Boot: SrcLab核心基础Spring Boot库
:toc:
:toclevels: 3
:toc-title: 目录
:last-update-label!:
Sun Qian <fredsuvn@163.com>
:encoding: UTF-8
:emaill: fredsuvn@163.com
:url: https://github.com/srclab-projects/boat-spring-boot
:license: https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license]

:qq-group: QQ group: 1037555759
:boat-url: https://github.com/srclab-projects/boat
:boat-spring-boot-version: 0.0.0

== 简介

Boat Spring Boot是一组基于{boat-url}[Boat]的spring-boot项目集合.
它在{boat-url}[Boat]的基础上, 提供了许多方便快捷的spring-boot接口, 函数和工具.

Boat Spring Boot包括:

* *boat-spring-boot-core*: 核心和基础的接口, 功能和工具, 比如spring bean操作;
* *boat-spring-boot-test*: 测试依赖管理, 用来在测试编译和运行范围下引入测试框架;
* *boat-spring-boot-bom*: Boat Spring Boot Bom.

根据Spring Boot官方推荐, 我们应当使用starter来导入Boat Spring Boot:

* boat-spring-boot-starter
* boat-spring-boot-starter-test
* boat-spring-boot-starter-bom

== 获取

.Gradle
[source,groovy,subs="attributes+"]
----
implementation("xyz.srclab.spring.boot:boat-spring-boot-starter:{boat-spring-boot-version}")
----

.Maven
[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>xyz.srclab.spring.boot</groupId>
    <artifactId>boat-spring-boot-starter</artifactId>
    <version>{boat-spring-boot-version}</version>
</dependency>
----

.Source Code
{url}

== 使用

=== Core (boat-spring-boot-starter)

==== Bean

Bean提供:

* BeanProperties: bean属性;
* BeanLifecyclePostProcessor: Spring Bean整个生命周期后置处理器;
* BeanRegistry: 动态bean注册.

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/bean/MyBeanRegistry.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/bean/MyBeanLifecyclePostProcessor.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/bean/MyBeanRegistry.kt[]
----

[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/bean/MyBeanLifecyclePostProcessor.kt[]
----

==== Task

Task提供:

* TaskPoolProperties: Task线程池属性;
* TaskExecutors: 快速创建TaskExecutor, 通常使用ThreadPoolProperties;
* TaskDelegate: Task调度委托.

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/task/MyTaskExecutorConfiguration.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/task/MyTaskExecutorConfigurationKt.kt[]
----

==== Schedule

Schedule提供:

* ScheduledPoolProperties: 调度线程池属性;
* TaskSchedulers: 快速创建TaskScheduler, 通常使用ScheduledPoolProperties.

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/schedule/MyTaskSchedulerConfiguration.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/schedule/MyTaskSchedulerConfiguration.kt[]
----

==== Exception

异常包提供:

* EnableExceptionService: 开启异常服务的注解;
* ExceptionStatusService: 自动注入的全局异常处理, 使用ExceptionStateHandler;
* ExceptionStatusHandler: 用户定义的bean, 用来装换异常到State.

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/exception/ExceptionServiceSample.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/exception/RuntimeExceptionStatusHandler.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/exception/ThrowableStatusHandler.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/exception/ExceptionServiceSample.kt[]
----

=== Web (boat-spring-boot-web-starter)

==== Exception

Web异常提供:

* EnableWebExceptionService: 开启web异常服务的注解;
* WebExceptionService: 自动注入的全局web异常处理服务, 使用WebExceptionHandler;
* WebExceptionHandler: 用户定义的处理异常的bean, 将异常转成返回值ResponseEntity.

.Java Examples
[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/exception/WebExceptionSample.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/exception/TestController.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/exception/RuntimeExceptionHandler.java[]
----

[source,java]
----
include::../boat-spring-boot-sample/src/test/java/sample/java/xyz/srclab/spring/boot/web/exception/ThrowableHandler.java[]
----

.Kotlin Examples
[source,kotlin]
----
include::../boat-spring-boot-sample/src/test/kotlin/sample/kotlin/xyz/srclab/spring/boot/web/exception/WebExceptionSample.kt[]
----

==== Utilities

一些工具类也在web中提供:

* WebExceptions: 提供异常相关的工具方法;
* WebServlets: 提供Servlet工具, 比如针对ServletRequest, ServletInputStream等的快速构建.

== 共享和联系方式

* {emaill}
* {url}
* {qq-group}

== License

{license}