= Boat Spring Boot: SrcLab Core Libraries for Spring Boot
Sun Qian <fredsuvn@163.com>
:encoding: UTF-8
:license: https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license]
:emaill: fredsuvn@163.com
:url: https://github.com/srclab-projects/boat-spring-boot
:qq: 1037555759
:boat-url: https://github.com/srclab-projects/boat
:boat-spring-boot-version: 0.1.0

image::../logo.svg[Boat Spring Boot]

== Revision

[options="header"]
|===
|Date|Revision|Author|Content
|2020-3-5|1.0.0|{author}|Old project
|2021-3-5|0.1.0|{author}|New project
|===

== Toc

* <<introduction>>
* <<getting>>
* <<usage>>
* <<contact>>
* <<license>>

[#introduction]
== Introduction

Boat Spring Boot is a set of spring-boot projects with {boat-url}[Boat].
It provides many fast and convenient interfaces, functions and utilities adapted to spring-boot with {boat-url}[Boat].

Boat Spring Boot includes:

* *boat-spring-boot-core*: Core and basic interfaces, functions and utilities, such as spring bean operation;
* *boat-spring-boot-test*: Test dependencies management, to import common test libraries in test scope;
* *boat-spring-boot-bom*: Boat Spring Boot Bom.

Following the official recommendation of Spring Boot, we should use starter to import Boat Spring Boot:

* boat-spring-boot-starter
* boat-spring-boot-starter-test
* boat-spring-boot-starter-bom

[#getting]
== Getting

=== Gradle

[source,groovy,subs="attributes+"]
----
implementation("xyz.srclab.spring.boot:boat-spring-boot-starter:{boat-spring-boot-version}")
----

=== Maven

[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>xyz.srclab.spring.boot</groupId>
    <artifactId>boat-spring-boot-starter</artifactId>
    <version>{boat-spring-boot-version}</version>
</dependency>
----

=== Source Code

https://github.com/srclab-projects/boat-spring-boot

[#usage]
== Usage

* <<usage-core>>
** <<usage-core-bean>>
** <<usage-core-task>>
** <<usage-core-schedule>>

[#usage-core]
=== Core (boat-spring-boot-starter)

[#usage-core-bean]
==== Bean

Bean provides:

* BeanLifecyclePostProcessor: Spring Bean lifecycle post processor;
* BeanRegistry: Dynamic bean registry.

===== Java Examples

[source,java]
----
@Component
public class MyBeanRegistry extends BeanRegistry {

    @NotNull
    @Override
    protected Map<String, Object> registeredSingletons() {
        Map<String, Object> result = new HashMap<>();
        result.put("bean1", "bean1");
        result.put("bean2", "bean2");
        return result;
    }

    @NotNull
    @Override
    protected Set<BeanProperties> registeredBeans() {
        Set<BeanProperties> result = new HashSet<>();
        BeanProperties beanProperties = new BeanProperties();
        beanProperties.setName("myBean");
        beanProperties.setClassName(MyBean.class.getName());
        result.add(beanProperties);
        return result;
    }
}
----

===== Kotlin Examples

[source,kotlin]
----
@Component
open class MyBeanRegistry : BeanRegistry() {

    override val registeredSingletons: Map<String, Any>
        get() {
            val result: MutableMap<String, Any> = HashMap()
            result["bean1"] = "bean1"
            result["bean2"] = "bean2"
            return result
        }

    override val registeredBeans: Set<BeanProperties>
        get() {
            val result: MutableSet<BeanProperties> = HashSet()
            val beanProperties = BeanProperties()
            beanProperties.name = "myBean"
            beanProperties.className = MyBean::class.java.name
            result.add(beanProperties)
            return result
        }
}
----

[#usage-core-task]
==== Task

Task provides:

* ThreadPoolProperties: Properties for thread pool;
* TaskExecutors: Help fast create TaskExecutor with ThreadPoolProperties.

===== Java Examples

[source,java]
----
@Configuration
@EnableAsync
public class MyTaskExecutorConfiguration {

    @Bean
    public TaskExecutor taskExecutor() {
        ThreadPoolProperties poolProperties = new ThreadPoolProperties();
        poolProperties.setThreadNamePrefix("6666");
        return TaskExecutors.newTaskExecutor(poolProperties);
    }
}
----

===== Kotlin Examples

[source,kotlin]
----
@Configuration
@EnableAsync
open class MyTaskExecutorConfigurationKt {

    @Bean
    open fun taskExecutor(): TaskExecutor {
        val poolProperties = ThreadPoolProperties()
        poolProperties.threadNamePrefix = "6666"
        return newTaskExecutor(poolProperties)
    }
}
----

[#usage-core-schedule]
==== Schedule

Schedule provides:

* ScheduledPoolProperties: Properties for scheduled thread pool;
* TaskSchedulers: Help fast create TaskScheduler with ScheduledPoolProperties.

===== Java Examples

[source,java]
----
@Configuration
@EnableScheduling
public class MyTaskSchedulerConfiguration {

    @Bean
    public TaskScheduler taskScheduler() {
        ScheduledPoolProperties poolProperties = new ScheduledPoolProperties();
        poolProperties.setThreadNamePrefix("6666");
        return TaskSchedulers.newTaskScheduler(poolProperties);
    }
}
----

===== Kotlin Examples

[source,kotlin]
----
@Configuration
@EnableScheduling
open class MyTaskSchedulerConfiguration {

    @Bean
    open fun taskScheduler(): TaskScheduler {
        val poolProperties = ScheduledPoolProperties()
        poolProperties.threadNamePrefix = "6666"
        return newTaskScheduler(poolProperties)
    }
}
----

[#contact]
== Contribution and Contact

* {emaill}
* {url}
* QQ group: 1037555759

[#license]
== License

{license}