= Boat Spring Boot: SrcLab核心基础Spring Boot库
Sun Qian <fredsuvn@163.com>
:encoding: UTF-8
:license: https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license]
:emaill: fredsuvn@163.com
:url: https://github.com/srclab-projects/boat-spring-boot
:qq: 1037555759
:boat-url: https://github.com/srclab-projects/boat
:boat-spring-boot-version: 0.1.0

image::../logo.svg[Boat Spring Boot]

== 修订

[options="header"]
|===
|日期|修订版|作者|内容
|2020-3-5|1.0.0|{author}|旧项目
|2021-3-5|0.1.0|{author}|新项目
|===

== 目录

* <<introduction>>
* <<getting>>
* <<usage>>
** <<usage-core>>
* <<contact>>
* <<license>>

[#introduction]
== 简介

Boat Spring Boot是一组基于{boat-url}[Boat]的spring-boot项目集合.
它在{boat-url}[Boat]的基础上, 提供了许多方便快捷的spring-boot接口, 函数和工具.

Boat Spring Boot包括:

* *boat-spring-boot-core*: 核心和基础的接口, 功能和工具, 比如spring bean操作;
* *boat-spring-boot-test*: 测试依赖管理, 用来在测试编译和运行范围下引入测试框架;
* *boat-spring-boot-bom*: Boat Spring Boot Bom.

根据Spring Boot官方推荐, 我们应当使用starter来导入Boat Spring Boot:

* boat-spring-boot-starter
* boat-spring-boot-starter-test
* boat-spring-boot-starter-bom

[#getting]
== 获取

=== Gradle

[source,groovy,subs="attributes+"]
----
implementation("xyz.srclab.spring.boot:boat-spring-boot-starter:{boat-spring-boot-version}")
----

=== Maven

[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>xyz.srclab.spring.boot</groupId>
    <artifactId>boat-spring-boot-starter</artifactId>
    <version>{boat-spring-boot-version}</version>
</dependency>
----

=== Source Code

https://github.com/srclab-projects/boat-spring-boot

[#usage]
== 使用

[#usage-core]
=== Spring Boot Core (boat-spring-boot-starter)

Core提供:

* SpringBeanPostProcessor: Spring的bean全局全生命周期后置处理器;
* SpringBeanRegistration: 动态bean注册.

==== Java Examples

[source,java]
----
@Component
public class BeanRegistration implements SpringBeanRegistration {

    @NotNull
    @Override
    public Map<String, Object> registerSingletons() {
        Map<String, Object> map = new HashMap<>();
        map.put("bean1", "bean1");
        return map;
    }

    @NotNull
    @Override
    public Set<SpringSingletonGenerator> registerSingletonGenerators() {
        Set<SpringSingletonGenerator> set = new HashSet<>();
        set.add(new SpringSingletonGenerator() {
            @NotNull
            @Override
            public String name() {
                return "bean2";
            }

            @NotNull
            @Override
            public Object generate() {
                return "bean2";
            }
        });
        return set;
    }
}
----

==== Kotlin Examples

[source,kotlin]
----
@Component
open class BeanRegistrationKt : SpringBeanRegistration {

    override fun registerSingletons(): Map<String, Any> {
        val map: MutableMap<String, Any> = HashMap()
        map["bean1Kt"] = "bean1Kt"
        return map
    }

    override fun registerSingletonGenerators(): Set<SpringSingletonGenerator> {
        val set: MutableSet<SpringSingletonGenerator> = HashSet()
        set.add(object : SpringSingletonGenerator {

            override val name: String = "bean2Kt"

            override fun generate(): Any {
                return "bean2Kt"
            }
        })
        return set
    }
}
----

[#contact]
== 共享和联系方式

* {emaill}
* {url}
* QQ群: 1037555759

[#license]
== License

{license}